language: python
python:
  - 3.6.10
env:
  - BUILD_TYPE="Release"

before_install:
  - sudo apt-get update
  - sudo apt-get install gfortran liblapack-pic liblapack-dev libnetcdf-dev libnetcdff-dev
  - pip install netCDF4
  - pip install xarray
  - pip install scipy
  - git clone --branch=master --depth=100 --quiet git://github.com/clawpack/clawpack
  - cd clawpack
  - git submodule init
  - git submodule update
  - rm -rf geoclaw
  - ln -s ../ geoclaw
  # Print versions being used
  - python -c "import numpy; print(numpy.__version__)"
  - python -c "import netCDF4; print(netCDF4.__version__)"

install:
  - export PYTHONPATH=${PWD}:$PYTHONPATH
  - export CLAW=${PWD}
  - export FC=gfortran
  - export NETCDF4_DIR=/usr

before_script:
  # Print CPU info for debugging purposes:
  - cat /proc/cpuinfo
  - gfortran -v
  - /usr/bin/f95 -v
  - echo "PYTHONPATH="$PYTHONPATH
  - echo "CLAW="$CLAW
  - echo "FC="$FC
  - echo "NETCDF4_DIR="$NETCDF4_DIR

script:
  - cd $CLAW/geoclaw
  - nosetests -sv

after_failure:
 - for failed_test_path in *_output ; do cat $failed_test_path/run_output.txt ; cat $failed_test_path/error_output.txt ; done

notifications:
  email: false
